name: Update repository list

env:
  SCRIPT_DIR: .github/scripts

permissions:
  contents: write

on:
  # This script runs at 00h00 every Sunday 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Run script
        run: python ${{ env.SCRIPT_DIR }}/fetch_projects.py
      
      - name: Commit changes to repository
        run: bash ${{ env.SCRIPT_DIR }}/commit-updated-list.sh